
[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[window]
dimensions = { columns = 120, lines = 30 }
decorations = "Full"
padding = { x = 3, y = 3 }
dynamic_padding = true
option_as_alt = "OnlyLeft"
# opacity = 0.8
# blur = true

[font]
# normal = { family = "FiraCode Nerd Font", style = "Regular" }

normal = { family = "BlexMono Nerd Font", style = "Regular" }
italic = { family = "BlexMono Nerd Font", style = "Light Italic" }
bold = { family = "BlexMono Nerd Font", style = "SemiBold" }
bold_italic = { family = "BlexMono Nerd Font", style = "SemiBold Italic" }

# normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
# italic = { family = "IosevkaTerm Nerd Font", style = "Light Italic" }
# bold = { family = "IosevkaTerm Nerd Font", style = "SemiBold" }
# bold_italic = { family = "IosevkaTerm Nerd Font", style = "SemiBold Italic" }

size = 13

[colors]
[colors.normal]
black = "#5050A0"

[general]
import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
    # "~/.config/alacritty/themes/themes/nord.toml"
    # "~/.config/alacritty/themes/themes/base16_default_dark.toml"
    # "~/.config/alacritty/themes/themes/vesper.toml"
    # "~/.config/alacritty/themes/themes/citylights.toml"
    # "~/.config/alacritty/themes/themes/ayu_dark.toml"
    # "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[terminal]

